apiVersion: v1
kind: Pod
metadata:
  name: multipod
spec:
  containers:
  - name: webserver
    image: nginx:1.14
    imagePullPolicy: Always
    ports:
    - containerPort: 80
      protocol: TCP
  - name: centos
    image: centos:7
    imagePullPolicy: Always
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]


# pod 안에 여러개의 container를 생성할 수 있다.

 