apiVersion: v1
kind: Pod
metadata:
  name: pod-annotation
  annotations:
    description: "This is a pod with annotations"
    version: "1.0"
spec:
  containers:
  - name: nginx
    image: nginx:1.14
    ports:
    - containerPort: 80 