apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers:
  - name: nginx-container
    image: nginx:1.14
    imagePullPolicy: Always
    ports:
    - containerPort: 80
      protocol: TCP

# 위 yml을 실행하려면 create를 해주면 된다.
# kubectl create -f webserver.yml


# 명령어로 실행하면 아래와 같다.
# kubectl run webserver --image=nginx:1.14 --port=80